/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/UEli4NNQGk6
 */
import Link from "next/link"
import Image from "next/image";

export function Contacto() {
  return (
    (<section className="w-full py-6 md:py-12 lg:py-16">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col gap-2 items-center justify-center text-center">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">Contacto</h2>
            <p
              className="text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Escribenos para darte el servicio que mejor se adapte a ti
            </p>
          </div>
          <div className="grid w-full grid-cols-2 gap-4 md:grid-cols-4 md:gap-8">
            <Link
              className="flex flex-col items-center justify-center p-4 rounded-lg border border-gray-200 bg-black shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
              href="#">
              <Image src="/Calendly.svg" alt="Calendy Icon" height="200" width="200" />
              <span className="text-xl font-medium">Agenda una llamada</span>
            </Link>
            <Link
              className="flex flex-col items-center justify-center p-4 rounded-lg border border-gray-200 bg-black shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
              href="#">
              <Image src="/whatsapp.svg" alt="Calendy Icon" height="100" width="100" />
              <span className="text-xl font-medium pt-10">WhatsApp</span>
            </Link>
            <Link
              className="flex flex-col items-center justify-center p-4 rounded-lg border border-gray-200 bg-black shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 "
              href="#">
              <Image src="/instagram.svg" alt="Calendy Icon" height="100" width="100" />
              <span className="text-xl font-medium pt-10">Instagram</span>
            </Link>
            <Link
              className="flex flex-col items-center justify-center p-4 rounded-lg border border-gray-200 bg-black shadow-sm transition-colors hover:bg-gray-50 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950"
              href="#">
              <Image src="/gmail.svg" alt="Calendy Icon" height="100" width="100" />
              <span className="text-xl font-medium pt-10">Email</span>
            </Link>
          </div>
        </div>
      </div>
    </section>)
  );
}


function CalendarCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="#87CEEB"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="18" height="18" x="3" y="4" rx="2" ry="2" />
      <line x1="16" x2="16" y1="2" y2="6" />
      <line x1="8" x2="8" y1="2" y2="6" />
      <line x1="3" x2="21" y1="10" y2="10" />
      <path d="m9 16 2 2 4-4" />
    </svg>)
  );
}


function MessageCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="#008000"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 21 1.9-5.7a8.5 8.5 0 1 1 3.8 3.8z" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="#FF0080"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function MailIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>)
  );
}
